---
project: "Analytics.USA.gov"
full_name: Analytics.USA.gov
name: dap
github:
- 18F/analytics.usa.gov
- 18F/analytics-reporter
- 18F/analytics-reporter-api
description: A lightweight dashboard that shows web traffic across the .gov domain.  
impact: We designed a website that makes public and easy to understand the website analytics from the .gov domain.   
owner_type: project
testable: true 
partners:
- General Services Administration
stage: beta
milestones:
- 'May 2012: Digital Government Strategy calls for a government-wide analytics program'
- 'May 2013: Digital Analytics Program announced'
- 'August 2014: Full Digital Analytics Program access expanded to all federal staff at participating agencies'
- 'March 2015: Analytics.USA.gov announced'
- 'December 2015: New features and expanded data feeds announced'
contact:
- dap@support.digitalgov.gov
stack: 
- jekyll
- bourbon
- neat
- d3
- node
- analytics-reporter
team: 
- github: tdlowden
  role: lead
  id: tim
- github: jmhooper
  role: lead
  id: jonathan
type: app
blogtag: analytics.usa.gov
licenses:
  analytics.usa.gov:
    name: Public Domain (CC0)
    url: https://github.com/18F/analytics.usa.gov/blob/18f-pages/LICENSE.md
  analytics-reporter:
    name: Public Domain (CC0)
    url: https://github.com/18F/analytics-reporter/blob/master/LICENSE.md
links:
- https://analytics.usa.gov
status: 
