
# The staging site uses 18F Pages, a prefix, and pulls from production data.
url: https://pages.18f.gov/analytics.usa.gov
baseurl: /analytics.usa.gov
data_url: https://s3.amazonaws.com/cg-ff27f612-cd16-4a76-94f8-628986af2158/data/live
